files: ""
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        parallel: false
        min_py_version: "3.10"

  - repo: local
    hooks:
      - id: xsoar-lint
        name: xsoar-lint
        description: Run xsoar-linter on the code in content packs
        entry: demisto-sdk xsoar-lint
        files: ^Packs\/.*\.py$
        exclude: _test\.py|\.vulture_whitelist\.py|test_data|tests_data|TestData
        require_serial: true
        language: system

      - id: validate
        name: validate
        description: validate content
        entry: demisto-sdk validate
        args:
          - --skip-pack-dependencies
          - --config-path=validation_config.toml
        pass_filenames: false
        language: system
        require_serial: true
        exclude: ^\.secrets_ignore$ 
